import math
import pyautogui

FIELD_IMAGE_WIDTH_PIXELS = 2601
FIELD_IMAGE_HEIGHT_PIXELS = 1291

FIELD_WIDTH_PIXELS = FIELD_IMAGE_WIDTH_PIXELS
FIELD_HEIGHT_PIXELS = FIELD_IMAGE_HEIGHT_PIXELS

FIELD_WIDTH_METERS = 16.59128
FIELD_HEIGHT_METERS = 8.211312

FIELD_WIDTH_OFFSET_PIXELS = 0
FIELD_HEIGHT_OFFSET_PIXELS = 0

def get_dist(x1, y1, x2, y2):
    return math.sqrt(((x1 - x2) ** 2) + ((y1 - y2) ** 2))
